package main

import (
	"nipatest/main/db"
	"nipatest/main/internal/repository"
	"nipatest/main/internal/ticket"
	"nipatest/main/router"

	_ "nipatest/main/docs"

	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
	// _ "github.com/xesina/golang-echo-realworld-example-app/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 127.0.0.1:1323
// @BasePath /api
func main() {
	r := router.New()

	v1 := r.Group("/api")

	d := db.Initialize()
	db.AutoMigrate(d)

	tr := repository.NewTicketRepo(d)
	tk := ticket.NewTicket(tr)

	tk.Register(v1)
	r.GET("/swagger/*", echoSwagger.WrapHandler)
	r.Logger.Fatal(r.Start(":1323"))
}
